[project]
name = "generative-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "mido>=1.3.3",
    "pyfluidsynth>=1.3.4",
    "python-rtmidi>=1.5.8",
    "scamp>=0.9.2.post3",
    "yfinance>=1.0",
]
